sudo: no
dist: stretch
group: edge
language: node_js
node_js:
  - "10"

script:
  - >
    git clean -dfx &&
    npm install &&
    npm run prepublish &&
    rm .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_KEY
  on:
    branch: master
