sudo: no
dist: stretch
group: edge
language: node_js
node_js:
  - "10"

script:
  - >
    git clean -dfx &&
    npm install &&
    npm install typedoc &&
    node_modules/.bin/typedoc --out doc/ --mode modules --ignoreCompilerErrors;
    npm run prepublish &&
    echo node_modules > .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_KEY
  on:
    branch: master
